CORPUS_DIR = '../corpus/'
STOPLIST_FILE = '../stoplist.txt'
DOCID_FILE = 'docids.txt'
TERMID_FILE = 'termids.txt'
TERM_INDEX_FILE = 'term_index.txt'
TOPICS_FILE = 'topics.xml'
CORPUS_GRADES_FILE = 'corpus.qrel'
